import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body className="bg-white dark:bg-gray-900">
        <Nav />
        <section className="w-full h-full">{children}</section>
      </body>
    </html>
  );
}
